logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.security: DEBUG

spring:
  profiles:
    active: dev

  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:C:/dev/workspace/score-now-admin2/src/main/resources/static/

  security:
    user:
      name: user
      password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scorenow_data?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: scorenow_user
    password: scorenow!2025
  #  datasource:
  #    url: jdbc:mysql://localhost:3307/scorenow_dev
  #    username: root
  #    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/scorenow_dev
    #  data:
    #    mongodb:
    #      uri: mongodb://root:1234@localhost:27018/scorenow_dev?authSource=admin

    redis:
      host: localhost
      port: 6379

betsapi:
  base-url: "https://api.betsapi.com"
  token: "242890-b6f8MQtzsP85gx"
  connect-timeout: 3
  read-timeout: 5

scorenow:
  inplay:
    seen:
      ttlSeconds: 21600 # 6시간
    scan:
      fixedDelayMs: 60000 # 1분
    worker:
      lineup:
        fixedDelayMs: 10000 # 10초
        maxRetry: 5 # 재큐잉 최대 5회

      detail:
        fixedDelayMs: 10000
    due:
      goals:
        intervalMs: 15000 # 15초
        batchSize: 30
      detail:
        intervalMs: 30000 # 30초
        batchSize: 30


